### ISSUE TITLE
one question&bug

### ISSUE THREAD

**Issue by barnett2010** [HearthSim/python-fsb5#12]
win 7 64
python27

There is a mistake

cmd
python extract.py 

   File "extract.py",line 29
      def print <self,*args>:
SyntaxError: invalid syntax 

How to deal with it？？？

**Comment by barnett2010** [comment]
Replaced  python3.0.1
There is a new problem

cmd 
python extract.py -0 b music.fsb
Traceback <most recent call last>:
 File"extract.py",line 3,in <module>
   import argparse
ImportError: No module named argparse

**Comment by barnett2010** [comment]
Which version of the python you are using

**Comment by synap5e** [comment]
Hey

The script is meant to run with python3. Argparse is part of python 3.2 and up so that would be why 3.0.1 isn't working.
Sorry it's not clear - that's my bad. I should note that in the the README.

**Comment by synap5e** [comment]
Noted as of 36279036b97416b45810da5a2453c64dd841a15a
