### ISSUE TITLE
Where should I put libogg and libvorbis dlls?

### ISSUE THREAD

**Issue by pold500** [HearthSim/python-fsb5#13]
Under Windows 10 x64 system?

**Comment by pold500** [comment]
Issue is resolved now.
I runned ProcessMonitor with right filter to listen for where it looks for the library, paths can be $(YourWindowsDir)\SysWOW64 or root directory of the script.

**Comment by synap5e** [comment]
Good to know you got it working - I'll update the relevant part of the README to be more clear

**Comment by chezyann** [comment]
What about osx systems ?
